FROM python:3.11.5
RUN useradd -u 1000 -U -m jenkins
RUN curl -LO "https://dl.k8s.io/release/v1.26.8/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
USER jenkins