apiVersion: apps/v1
kind: Deployment
metadata:
  name: garmin
  namespace: default
  labels:
    k8s-app: garmin
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: garmin
  template:
    metadata:
      name: garmin
      labels:
        k8s-app: garmin
    spec:
      containers:
        - name: garmin
          image: ghcr.io/dekeyrej/garmin:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          securityContext:
            privileged: false
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: app-config
      imagePullSecrets:
        - name: ghcr-login-secret
