apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfl
  namespace: default
  labels:
    k8s-app: nfl
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nfl
  template:
    metadata:
      name: nfl
      labels:
        k8s-app: nfl
    spec:
      containers:
        - name: nfl
          image: localhost:32000/nfl:registry
          imagePullPolicy: Always
          ports:
          - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          securityContext:
            privileged: false
      imagePullSecrets:
        - name: regcred
