apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
  namespace: default
  labels:
    k8s-app: events
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: events
  template:
    metadata:
      name: events
      labels:
        k8s-app: events
    spec:
      containers:
        - name: events
          image: ghcr.io/dekeyrej/events:latest
          imagePullPolicy: Always
          env:
            - name: PERIOD
              value: "3593"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: secretcfg-volume
              mountPath: /code/secretcfg.json
              subPath: secretcfg.json
            - name: secretdef-volume
              mountPath: /code/secretdef.json
              subPath: secretdef.json
            - mountPath: /code/events.json
              name: events
              subPath: events.json
          securityContext:
            privileged: false
      volumes:
        - name: secretcfg-volume
          configMap:
            name: secretcfg
        - name: secretdef-volume
          configMap:
            name: secretdef
        - name: events
          configMap:
            name: matrix-events
      imagePullSecrets:
        - name: ghcr-login-secret
