apiVersion: apps/v1
kind: Deployment
metadata:
  name: garmin
  namespace: default
  labels:
    k8s-app: garmin
spec:
  replicas: 0
  selector:
    matchLabels:
      k8s-app: garmin
  template:
    metadata:
      name: garmin
      labels:
        k8s-app: garmin
    spec:
      containers:
        - name: garmin
          image: ghcr.io/dekeyrej/garmin:latest
          imagePullPolicy: Always
          env:
            - name: PERIOD
              value: "601"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: secretcfg-volume
              mountPath: /code/secretcfg.json
              subPath: secretcfg.json
            - name: secretdef-volume
              mountPath: /code/secretdef.json
              subPath: secretdef.json
          securityContext:
            privileged: false
      volumes:
        - name: secretcfg-volume
          configMap:
            name: secretcfg
        - name: secretdef-volume
          configMap:
            name: secretdef
      imagePullSecrets:
        - name: ghcr-login-secret
