apiVersion: apps/v1
kind: Deployment
metadata:
  name: github
  namespace: default
  labels:
    k8s-app: github
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: github
  template:
    metadata:
      name: github
      labels:
        k8s-app: github
    spec:
      containers:
        - name: github
          image: ghcr.io/dekeyrej/github:latest
          imagePullPolicy: Always
          env:
            - name: PERIOD
              value: "599"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: secretcfg-volume
              mountPath: /code/secretcfg.json
              subPath: secretcfg.json
            - name: secretdef-volume
              mountPath: /code/secretdef.json
              subPath: secretdef.json
          securityContext:
            privileged: false
      volumes:
        - name: secretcfg-volume
          configMap:
            name: secretcfg
        - name: secretdef-volume
          configMap:
            name: secretdef
      imagePullSecrets:
        - name: ghcr-login-secret
