apiVersion: apps/v1
kind: Deployment
metadata:
  name: github
  namespace: default
  labels:
    k8s-app: github
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: github
  template:
    metadata:
      name: github
      labels:
        k8s-app: github
    spec:
      containers:
        - name: github
          image: ghcr.io/dekeyrej/github:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          securityContext:
            privileged: false
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: app-config
            - secretRef:
                name: matrix-secret-environment
      imagePullSecrets:
        - name: ghcr-login-secret
