apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlb
  namespace: default
  labels:
    k8s-app: mlb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mlb
  template:
    metadata:
      name: mlb
      labels:
        k8s-app: mlb
    spec:
      containers:
        - name: mlb
          image: ghcr.io/dekeyrej/mlb:dev
          imagePullPolicy: Always
          env:
          - name: PERIOD
            value: "29"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
          - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          securityContext:
            privileged: false
      imagePullSecrets:
        - name: ghcr-login-secret
