apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycal
  namespace: default
  labels:
    k8s-app: mycal
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mycal
  template:
    metadata:
      name: mycal
      labels:
        k8s-app: mycal
    spec:
      containers:
        - name: mycal
          image: ghcr.io/dekeyrej/mycal:latest
          imagePullPolicy: Always
          env:
          - name: PERIOD
            value: "877"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
          - containerPort: 10255
          livenessProbe:
            tcpSocket:
              port: 10255
            initialDelaySeconds: 15
            periodSeconds: 30
          securityContext:
            privileged: false
      imagePullSecrets:
        - name: ghcr-login-secret
