apiVersion: v1
kind: ConfigMap
metadata:
  name: secretdef
  namespace: default
data:
  secretdef.json: |
    {
      "transit_key": "aes256-key",
      "namespace": "default", 
      "secret_name": "matrix-secrets",
      "read_type": "SECRET",
      "read_key": "secrets.json"
    }
