name: matrix build
on:
  push:
    branches: [ "main" ]
jobs:
  read-builds:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.read-builds.outputs.apps }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read builds.json
        id: read-builds
        run: |
          builds_file='builds.json'
          if [[ -f "$builds_file" ]]; then
            apps=$(cat "$builds_file")
            echo "Apps to build: $apps"
          else
            echo "builds file not found"
          fi
          echo "::set-output name=apps::$apps"

  build-apps:
    needs: read-builds
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.read-builds.outputs.apps)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          build-args: "MICROSERVICE=${{matrix.app}}"
          tags: "ghcr.io/dekeyrej/${{matrix.app}}:latest"
      # - name: Echo matrix values
      #   run: |
      #     echo "Matrix values: ${{ matrix.app }}"
