name: Selective Build and Push

on:
  push:
    branches:
      - main

jobs:
  determine-modified-files:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.determine-apps.outputs.apps }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Determine modified files
        id: determine-apps
        run: |
          python utilities/latest_and_last_successful.py
          modified_files=$(git diff-tree --no-commit-id --name-only -r ${{ steps.determine-apps.outputs.latest_sha }} ${{ steps.determine-apps.outputs.last_successful_sha }})
          echo "Modified files: $modified_files"
          apps_to_build=$(python -c "
          import build_data
          modified_files = '${modified_files}'.split()
          apps = set()
          for file in modified_files:
              if file in build_data.reverse_dependencies:
                  app = build_data.reverse_dependencies[file]
                  if app == 'all':
                      apps.update(build_data.services)
                  else:
                      apps.add(app)
          print(list(apps))
          ")
          echo "Apps to build: $apps_to_build"
          echo "::set-output name=apps::$apps_to_build"

  build-and-push:
    needs: determine-modified-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.determine-modified-files.outputs.apps) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: MICROSERVICE=${{ matrix.app }}
          tags: ghcr.io/dekeyrej/${{ matrix.app }}:latest