name: Selective Build and Push

on:
  push:
    branches:
      - main

jobs:
  determine-modified-files:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ env.apps_to_build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Determine modified files
        id: determine-apps
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          apps=$(python utilities/latest_and_last_successful.py)
          echo "apps=$apps" >> $GITHUB_ENV

      - name: show apps to build
        id: show-apps
        run: | 
          echo "Apps to build: $apps"

  build-and-push:
    needs: determine-modified-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.determine-modified-files.outputs.apps) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: show apps to build
        id: show-apps
        run: | 
          echo "Apps to build: ${{ matrix.app }}"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: MICROSERVICE=${{ matrix.app }}
          tags: ghcr.io/dekeyrej/${{ matrix.app }}:latest